version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: gym_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
